### ISSUE TITLE
why I trained binary model is bigger than the original model?

### ISSUE THREAD

**Issue by Weyne168** [MatthieuCourbariaux/BinaryNet#10]
hi,
I use the Lasagne to train a mlp model and cnn model on mnist, and get their ”model.npz” files.
I found that the size of  binary net  ”model.npz”  is larger than the  ”model.npz” of mlp and cnn.
Is that means the binary net will use more parameters and cost too much memory???

**Comment by MatthieuCourbariaux** [comment]
> I found that the size of binary net ”model.npz” is larger than the ”model.npz” of mlp and cnn. Is that means the binary net will use more parameters and cost too much memory???

Those are the full precision training weights.
You might want to:
1. Binarize them with the sign function
2. Concatenate them in int32 variables.
3. Store them in a file.
