### ISSUE TITLE
could you share your cifar-10 test code

### ISSUE THREAD

**Issue by skyfuture2026** [MatthieuCourbariaux/BinaryNet#12]
Hello, I am working no cifar-10 binay network. I used your cifar-10 training code, and then I wrote my own testing code for ciffar-10. Generally I binarized conv2d layer weights and dense layer weights, but after binarizing conv2d layer weights, I couldn't get the right results. (I used deterministic to binarize)
So I am wondering am I understanding BNN correctly, or is it possible for you to share your cifar-10 test code?
Thank you very much!

**Comment by ofirliba** [comment]
hi skyfuturesky ,
did you succeed to create a runtime code for cifar10? 
If you could share your code as well as cifar10 train parameters file  , I would appreciate it very much!

thank you!

**Comment by skyfuture2026** [comment]
Hello, thank you so much for your reply. Actually I have already solved the problem.
I can create a runtime code for cifar10, it turns out to be an issue in binary_net.py. 
In the line 165, I added the following code segment:

    def get_output_for(self, input, deterministic=False, **kwargs):

        self.Wb = binarization(self.W, self.H, self.binary, deterministic, self.stochastic, self._srng)
        Wr = self.W
        self.W = self.Wb

        rvalue = super(Conv2DLayer, self).get_output_for(input, **kwargs)

        self.W = Wr

        return rvalue

Now testing result is correct.

Best,
Yuteng

**Comment by ofirliba** [comment]
hi,
Thanks for your replay. cifar10.py in train folder works fine.

Sorry for the miss understanding ,but what I'm looking for is cifar10 runtime ( like mnist.py in runtime folder) code using xnor/baseline/theano kernels in Dense and conv2D layers.
if you have this code it would be wonderful. 

do you have any idea if those optimized kernels can be also implemented in conv2DLayer? 

thanks,
Ofir

**Comment by skyfuture2026** [comment]
In runtime folder, only mnist.py is provided. You are right, there is no conv2DLayer in runtime folder, what I did was to modify the code in training folder to run testing.
