### ISSUE TITLE
How to revise it to be only activation is binary?

### ISSUE THREAD

**Issue by zxzhijia** [MatthieuCourbariaux/BinaryNet#18]
I'm wondering whether it is easy to revise the code to be only binarized activation without binary weights?

**Comment by MatthieuCourbariaux** [comment]
You might want to change the following lines: 
https://github.com/MatthieuCourbariaux/BinaryNet/blob/master/Train-time/cifar10.py#L48
https://github.com/MatthieuCourbariaux/BinaryNet/blob/master/Train-time/cifar10.py#L57

**Comment by zxzhijia** [comment]
I see. So should I just set W_LR_scale = 1? (the second line you mentioned)

**Comment by zxzhijia** [comment]
In addition, I tried to change the activation function to be relu instead of sigmoid or tanh. But it seems doesn't work well. Below is the code I changed:

def hard_relu(x):
      return T.clip(x,0,1)

def binary_relu_unit(x):
      return round3(hard_relu(x))
