### ISSUE TITLE
bias binarization

### ISSUE THREAD

**Issue by dlobato** [MatthieuCourbariaux/BinaryNet#26]
Hi,

Is there any expecial reason not to binarize the bias parameters in a similar way to weights?

Thanks you!

**Comment by MatthieuCourbariaux** [comment]
I do not think it is necessary to binarize the biases, as there are only very few of them (1 per neuron).
That being said, it may be possible to binarize them without reducing performance (validation accuracy).

**Comment by dlobato** [comment]
Thanks for the suggestion! I'll try to implement that to test. I'd like to implement inference on an FPGA and it'd be great to have every single parameter as a binarized value.

By the way, great job and great contribution!
