### ISSUE TITLE
Activation Binarization

### ISSUE THREAD

**Issue by EthanZhangYC** [MatthieuCourbariaux/BinaryNet#28]
Hi, you have mentioned in another issue that we don't need to binarize the input because previous layer could guarantee the binary input. But after passing a BatchNormalization layer, the previous output become full-precision again.  Is that something I have missed?

**Comment by MatthieuCourbariaux** [comment]
Hi Ethan, in our work, we binarize the output of the BatchNormalization layer, i.e.:

    Input -> convolution layer -> BatchNormalization layer -> sign layer -> convolution layer -> ...

As a result, all but the first convolution layer have binary inputs.
Does it answer your question?

**Comment by EthanZhangYC** [comment]
Hi Matthieu,

Thanks a lot for your reply. I misunderstood your NonlinearityLayer before since I considered it as a ReLu layer. Did you use any ReLu layers in your Cifar-10 model?

**Comment by MatthieuCourbariaux** [comment]
As far as I remember, we replaced all ReLU layers with the sign function.

**Comment by EthanZhangYC** [comment]
Oh I see, thank you so much.
