### ISSUE TITLE
binary_net.py syntax error

### ISSUE THREAD

**Issue by Cyndilee** [MatthieuCourbariaux/BinaryNet#3]
Hi,
I'm trying to run mnist.py. But there is SyntaxError in binary_net.py line 40. Any idea why does this error occur? BTW, I'm using Python 3.5.

Thanks.

**Comment by MatthieuCourbariaux** [comment]
Hi,

I suggest you try again with Python 2.7. instead of Python 3.5.
Please tell me if the SyntaxError disappears.

Cheers,

Matthieu

**Comment by jli05** [comment]
FYI you could run the command 2to3 to adapt Python 2.7 code to 3.5. Then you can hand fix remaining problems.

**Comment by MatthieuCourbariaux** [comment]
OK, thank you for the tip.

Matthieu

**Comment by Cyndilee** [comment]
Thanks all. I've fixed it by using Python 2.7.
