### ISSUE TITLE
AttributeError: 'module' object has no attribute 'BatchNormLayer'

### ISSUE THREAD

**Issue by linzihyuan** [MatthieuCourbariaux/BinaryNet#31]
Hi
I use theano (ver. = 0.8) in the anaconda and execute "python mnist.py"
The following error message appears：
![default](https://user-images.githubusercontent.com/43560196/52777737-709fa000-307f-11e9-8964-4082810fa40c.PNG)

How can I solve it?
Thanks!

**Comment by linzihyuan** [comment]
I found a solution.
After updating the version of lasagne, it will be able to solve (0.1 -> 0.2)

Thanks!

**Comment by RomanFoell** [comment]
How did you manage to update to version 0.2 for lasagne.
I encountered the same issue, but conda install or upgrade did not work for me.

Thanks.

**Comment by RomanFoell** [comment]
Ok, I think I got around this by simply downloading lasagne 0.2 from here:

https://anaconda.org/Toli/lasagne/files

and replacing the packages manually in my environment.
