### ISSUE TITLE
How to extract trained binarized weights with BinaryNet

### ISSUE THREAD

**Issue by changchun-zhou** [MatthieuCourbariaux/BinaryNet#33]

**Comment by JordyDH** [comment]
You can read the weight parameters and use the a sign function that is used is Run-Time

**Comment by JanashreeA** [comment]
Can i extract the weights at train time itself?

**Comment by MatthieuCourbariaux** [comment]
Yes, you can extract the weights at any time during training. Just apply the sign function to the full precision latent weight matrix.
