### ISSUE TITLE
The weights, and biases of the conv and bn are not binary (They are floats) ! 

### ISSUE THREAD

**Issue by negative-slack** [MatthieuCourbariaux/BinaryNet#38]
Hi, after training the model, I checked the weights, and the biases of each conv and bn layers and they are floats. I am not sure what I am missing here, but the paper specifically talked about the weights and activations being constrained to +1/-1, which is not the case !! I appreciate any help here !

**Comment by MatthieuCourbariaux** [comment]
Hi, 
For inference / run-time, you only need the weights' signs. You can discard the rest of the data. You will get the performance reported in the paper.
If I remember correctly, we did not quantized the biases. but I may be wrong.

**Comment by negative-slack** [comment]
Thank you for your reply, I appreciate it.
